apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projectmappings.kubetruth.cloudtruth.com
spec:
  group: kubetruth.cloudtruth.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                scope:
                  type: string
                  description: Root or override scope, there can only be one root scope
                  enum: ["root", "override"]
                  default: "override"
                project_selector:
                  type: string
                  description: A regexp to limit the projects acted against (client-side).  Supplies any named matches for template evaluation
                key_selector:
                  type: string
                  description: A regexp to limit the keys acted against (client-side).  Supplies any named matches for template evaluation
                key_filter:
                  type: string
                  description: Limits the keys fetched to contain the given substring (server-side, api search param)
                configmap_name_template:
                  type: string
                  description: The template to use in generating ConfigMap names
                secret_name_template:
                  type: string
                  description: The template to use in generating Secret names
                namespace_template:
                  type: string
                  description: The template to use in generating namespace names
                key_template:
                  type: string
                  description: The template to use in generating key names
                skip:
                  type: boolean
                  description: Skips the generation of resources for the selected projects
                skip_secrets:
                  type: boolean
                  description: Prevent transfer of secrets to kubernetes Secrets
                included_projects:
                  type: array
                  items:
                    type: string
                  description: Include the parameters from other projects into the selected ones.  This is non-recursive, so if A imports B and B imports C, then A will only get B's parameters.  For key conflicts, if A includes [B, C], then the precendence is A overrides C overrides B.
              required:
                - scope
      additionalPrinterColumns:
        - name: Scope
          type: string
          description: The scope of the project mapping
          jsonPath: .spec.scope
        - name: Project
          type: string
          description: The selector used to target configuration by project
          jsonPath: .spec.project_selector
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: projectmappings
    singular: projectmapping
    kind: ProjectMapping
    shortNames:
      - pm
