{{- if and .Values.rbac.create .Values.rbac.clusterInstall }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubetruth.fullname" . }}
rules:
  {{- with .Values.rbac.roleRules }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.rbac.additionalRoleRules }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
