apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubetruth.fullname" . }}
  namespace:  {{ .Release.Namespace }}
  labels:
    {{- include "kubetruth.labels" . | nindent 4 }}
data:
  kubetruth.yaml: |-
    # Configures how kubetruth fetches and maps parameters from CloudTruth to Kubernetes

    #
    # The following settings can all be overriden on a per-project basis in project_overrides
    #

    # Uses the given regexp to limit the projects acted against (client-side).  Supplies any named matches for template evaluation
    # project_selector: ""

    # Uses the given regexp to limit the keys acted against (client-side).  Supplies any named matches for template evaluation
    # key_selector: ""

    # Limits the keys fetched to contain the given substring (server-side, api search param)
    # key_filter: ""

    # The template to use in generating ConfigMap names
    # configmap_name_template: "%{project}"
    # The template to use in generating Secret names
    # secret_name_template: "%{project}"
    # The template to use in generating namespace names
    # namespace_template: ""
    # The template to use in generating key names
    # key_template: "%{key}"

    # Skips the generation of resources for the selected projects.  Useful for
    # excluding projects that should only be included into others.
    # skip: false

    # Do not transfer secrets to kubernetes resources
    # skip_secrets: false

    # Include the data from other projects into the selected ones
    # included_projects: []

    # Override any of the above settings for specific projects by name pattern
    # project_overrides:
    #  - project_selector: oddballProject
    #    configmap_name_template: special-name
    #  - project_name: someOtherProject
    #    key_template: %{key_upcase}
