{{- if .Values.rbac.create }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kubetruth.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    #    resourceNames: ["my-secret"]
    verbs: ["get", "list", "create", "update", "delete"]

{{- end -}}
