{{- if and .Values.rbac.create (not .Values.rbac.clusterInstall) }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "kubetruth.fullname" . }}
rules:
  {{- with .Values.rbac.roleRules }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.rbac.additionalRoleRules }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end -}}
