# Setup the kubetruth CRD to ignore all projects except for the one named deploytest
# For the deploytest project, get the resource template from the cloudtruth template named deployment
projectMappings:

  # Define the root project mapping, skipping all projects except for the
  # example we care about
  root:
    scope: "root"
    environment: default
    skip: true

  # Define an override ProjectMapping to create kubetruth CRDs from the
  # CloudTruth project named kubetruth
  kubetruth:
    scope: "override"
    skip: false
    project_selector: "^kubetruth$"
    resource_templates:
      # Disable default templates for this project as they aren't needed
      configmap: ""
      secret: ""

      crds: |
        {%- for template in templates.names %}
        {{ templates[template] }}
        {% unless forloop.last %}---{% endunless %}
        {%- endfor %}
