name: CD

on: push

env:
  CI: true
  CLOUDTRUTH_API_KEY: ${{ secrets.CLOUDTRUTH_API_KEY }}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master # this will use by default the .ruby-version file

      - name: Install cloudtruth cli
        uses: cloudtruth/cli-action@v1
        with:
          version: 0.4.0

      - run: cloudtruth -e production template get deploy.coveralls_yml > .coveralls.yml

      - run: ruby -v
      - run: gem install --no-document bundler
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rspec

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cloudtruth cli
        run: |
          curl -Lsf https://github.com/cloudtruth/cloudtruth-cli/releases/download/0.1.0/cloudtruth_0.1.0_amd64.deb  -o /tmp/cloudtruth.deb
          sudo dpkg -i /tmp/cloudtruth.deb

      - name: Install Atmos
        run: sudo gem install --no-document simplygenius-atmos

      - name: Setup Atmos
        run: |
          mkdir -p config
          cloudtruth -e production template get deploy.atmos_yml > config/atmos.yml

      - name: Build the Docker image
        run: |
          docker build --target release -t kubetruth .

      - name: Push the Docker image
        run: |
          tag=${GITHUB_REF##*/v}
          echo "Pushing version '$tag' to docker hub"
          source <(cloudtruth -e production template get deploy.docker_credentials_env)
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

          docker tag kubetruth cloudtruth/kubetruth:latest
          docker push cloudtruth/kubetruth:latest
          docker tag kubetruth cloudtruth/kubetruth:${tag}
          docker push cloudtruth/kubetruth:${tag}

      - name: Package helm chart
        run: |
          source <(cloudtruth -e production template get deploy.helm_package_env)
          mkdir -p tmp/packaged-chart/
          (cd tmp/packaged-chart && helm package ../../helm/kubetruth)
          ./bin/generate-helmv2.sh
          (cd tmp/packaged-chart && helm package ../../tmp/helmv2/kubetruth)
          maybe_merge=""
          if curl -sfL ${HELM_REPO_URL}/index.yaml -o tmp/old-index.yaml; then
            maybe_merge="--merge tmp/old-index.yaml"
          fi
          helm repo index ${maybe_merge} --url ${HELM_REPO_URL} tmp/packaged-chart/

      - name: Deploy helm chart to S3
        run: |
          source <(cloudtruth -e production template get deploy.aws_credentials_env)
          source <(cloudtruth -e production template get deploy.helm_package_env)
          atmos -e production auth_exec aws s3 sync tmp/packaged-chart/ s3://${BUCKET_NAME}/${BUCKET_PATH}/

          assets=""
          for asset in tmp/packaged-chart/*; do
            asset=${asset##*/}
            asset="/${BUCKET_PATH}/${asset}"
            assets="${assets} ${asset}"
          done
          atmos -e production auth_exec aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths ${assets}
